### ISSUE TITLE
feat: Better template formatting options.

### ISSUE THREAD

**Issue by saul-jb** [kuvaus/LlamaGPTJ-chat#12]
It would be nice to have more formatting options like being able to wrap the output in certain tokens to assist with reading from stdout.

The following is an example format, altering the users input and the models output:
```
### Instruction:
The prompt below is a question to answer, write an appropriate response.
### Prompt:
How many words does the sentence '%1' have?
### Response:
<START>%2<FINISH>
```

This sort of behavior may be possible asking the model to format it in a specific way but that is error prone and may not work on all models.

Furthermore, it would be nice to have more information about the template format and how it is parsed and what parts are important. (E.g. are the `#` symbols before the headers important? Can they be replaced with other symbols or removed?)

**Comment by saul-jb** [comment]
> I need to think if there is a nice and simple way to do it without changing the response function. Right now it just dumps the response on stdout.

Perhaps this is common enough to just add it to the CLI parameters.

> The simplest way I could think of was just that the template does not care how the lines are formatted. Only the `%1` (user input) line is important.

I thought this might be the case but with LLMs it is a bit hard to test and know for sure. A couple follow ups: If the template is given to the LLM as is there should be no issues with reducing the template to just `%1` allowing the prompter to specify the template with every prompt? If dynamic templates can't be done this way then could there be a way to load templates in and out perhaps in a similar fashion to `/save` & `/load`?

**Comment by kuvaus** [comment]
> Perhaps this is common enough to just add it to the CLI parameters.
> 
Yup. Now in v0.2.5 with `--b_token` and `--e_token`.

> > The simplest way I could think of was just that the template does not care how the lines are formatted. Only the `%1` (user input) line is important.
> 
> I thought this might be the case but with LLMs it is a bit hard to test and know for sure. A couple follow ups: If the template is given to the LLM as is there should be no issues with reducing the template to just `%1` allowing the prompter to specify the template with every prompt?

Yeah, should be possible. You might need to add some empty newlines in case the loading function happens to give errors:

```


%1

```

And then just have a way more elaborate prompt.


> If dynamic templates can't be done this way then could there be a way to load templates in and out perhaps in a similar fashion to `/save` & `/load`?

Good point. This is something I could maybe add in a future version.

**Comment by saul-jb** [comment]
> Yup. Now in v0.2.5 with `--b_token` and `--e_token`.

Thanks, that makes things much easier.

> Yeah, should be possible. You might need to add some empty newlines in case the loading function happens to give errors:

Thanks, I was missing the newlines.

> > If dynamic templates can't be done this way then could there be a way to load templates in and out perhaps in a similar fashion to `/save` & `/load`?
> 
> Good point. This is something I could maybe add in a future version.

Since empty templates work this is probably not that important since users can wrap the program and provide their own system for changing templates.

Thanks heaps for all your fast work, this now has all the required functionality to do anything I can think of for now, so I'm closing this issue.
