### ISSUE TITLE
Converting Models from .pth to .ggml

### ISSUE THREAD

**Issue by ardywibowo** [kuvaus/LlamaGPTJ-chat#5]
Hello,
I wanted to ask how you are able to convert the MPT-7B weights from the HuggingFace checkpoints to .ggml. Is there a guide to this? Does the llama.cpp repo conversion code work out of the box?

Thanks!

**Comment by kuvaus** [comment]
Good question!
I haven't actually done the conversion myself so I can't say for sure.

What I know is that the backend currently has a slightly modified version of llama.cpp (that got updated yesterday) that has MPT support. There's lots of work going on right now with both gp4all and ggml/llama.cpp people to make it work with regular llama.cpp.

You're right, Llama.cpp indeed has a quantization tool to convert models to ggml! It might be that you need to use the backend llama tools: If you want to use the quantization tools of the backend Llama.cpp, just uncomment this line in the LlamaGPTJ-chat `CMakeLists.txt` and build like normal:

```cmake
change:
#set(LLAMA_BUILD_EXAMPLES ON CACHE BOOL "llama: build examples" FORCE)
to:
set(LLAMA_BUILD_EXAMPLES ON CACHE BOOL "llama: build examples" FORCE)
```

Then you all the llama.cpp tools and examples in the `./bin` folder in addition with `./bin/chat`. Unless I'm totally wrong, I think `./bin/quantize` is the tool to use.
So maybe something like this:
```bash
./bin/quantize huggingface-mpt-version.pth ggml-mpt-version.bin
```
Not sure if it works, I haven't tried. (I assume the pth file contains the whole model, not just the changes to base model).

But converting huggingface models to ggml is something I kinda want to try that at some point too! It sounds very interesting.

I hope this helps a bit. If you want more more info, check the GPT4All discord from their github page: https://github.com/nomic-ai/gpt4all People who have actually converted MPT models hang around there I think.

**Comment by kuvaus** [comment]
I'm assuming you got it working. Reopen the issue or let me know if I messed up. :)
