### ISSUE TITLE
How give context

### ISSUE THREAD

**Issue by diegofazio** [kuvaus/LlamaGPTJ-chat#8]
How can I add a context? For example, I would like to create a chatbot which would ask me to select between 3 products.
1) Apple
2) Strawberry
3) Orange.
And then ask what product I want and how much. How do I create that context?

Diego.

**Comment by MBCX** [comment]
To do this, you must first create a "prompt template" text file. Then, give the correct system message to the assistant, and then load the template when you load the program.

So something like this would work.

"promptTemplate.txt"
```plain
### Instruction:
You are managing a fruit shop that sells three items: apples, strawberries, and oranges. Listen to what the user requests and respond accordingly.
### Prompt:
%1
### Response:
```
Then, to load the template when you load the program:
```bash
./chat-program --model "your model" --load_template "./promptTemplate.txt"
```

**Comment by diegofazio** [comment]
Thanks! Which model do you recommend for this job?

Diego

**Comment by MBCX** [comment]
Models that have lots of parameters (B) will be better. However, those are always bigger in size and will take longer to generate the answers.

[You can click here](https://github.com/nomic-ai/gpt4all/tree/main/gpt4all-chat#manual-download-of-models) to see all the models you can use. As a base, you should be fine with [ggml-gpt4all-j-v1.3-groovy](https://gpt4all.io/models/ggml-gpt4all-j-v1.3-groovy.bin)

**Comment by kuvaus** [comment]
This looks like it works now. Please reopen this issue if I made any mistakes :)
